In [1]:
import pandas as pd
import numpy as np

In [3]:
telemetry = pd.read_csv(
    "../data_pack/raw/turbine_telemetry_14day_sample.csv"
)

dam = pd.read_csv(
    "../data_pack/raw/dam_price_14day_sample.csv"
)

In [4]:
telemetry["timestamp"] = pd.to_datetime(
    telemetry["timestamp"]
)

dam["timestamp"] = pd.to_datetime(
    dam["timestamp"]
)

In [5]:
print("Telemetry shape:", telemetry.shape)
print("DAM shape:", dam.shape)

print("\nTelemetry:")
display(telemetry.head())

print("\nDAM:")
display(dam.head())

Telemetry shape: (1680, 5)
DAM shape: (336, 2)

Telemetry:

   timestamp turbine_id  wind_speed  power_kw  availability
0 2026-03-01        T01        7.11     198.3           1.0
1 2026-03-01        T02        5.42      25.6           1.0
2 2026-03-01        T03        8.31     393.2           1.0
3 2026-03-01        T04        4.82      11.3           1.0
4 2026-03-01        T05        4.24      27.3           1.0

DAM:

            timestamp  dam_price_inr_per_kwh
0 2026-03-01 00:00:00                  4.255
1 2026-03-01 01:00:00                  4.330
2 2026-03-01 02:00:00                  4.186
3 2026-03-01 03:00:00                  4.032
4 2026-03-01 04:00:00                  4.141

Basic Validation

In [6]:
print("Telemetry missing values:")
print(telemetry.isna().sum())

print("\nDAM missing values:")
print(dam.isna().sum())

Telemetry missing values:
timestamp       0
turbine_id      0
wind_speed      0
power_kw        0
availability    0
dtype: int64

DAM missing values:
timestamp                0
dam_price_inr_per_kwh    0
dtype: int64

In [7]:
print("Telemetry missing values:")
print(telemetry.isna().sum())

print("\nDAM missing values:")
print(dam.isna().sum())

Telemetry missing values:
timestamp       0
turbine_id      0
wind_speed      0
power_kw        0
availability    0
dtype: int64

DAM missing values:
timestamp                0
dam_price_inr_per_kwh    0
dtype: int64

In [10]:
print(
    "Duplicate telemetry rows:",
    telemetry.duplicated().sum()
)

print(
    "Duplicate DAM rows:",
    dam.duplicated().sum()
)

Duplicate telemetry rows: 0
Duplicate DAM rows: 0

In [9]:
print(
    "Telemetry time range:",
    telemetry["timestamp"].min(),
    "→",
    telemetry["timestamp"].max()
)

print(
    "DAM time range:",
    dam["timestamp"].min(),
    "→",
    dam["timestamp"].max()
)

Telemetry time range: 2026-03-01 00:00:00 → 2026-03-14 23:00:00
DAM time range: 2026-03-01 00:00:00 → 2026-03-14 23:00:00

In [12]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [6]:
from part_a.tools.data_tools import DataQueryTool

tool = DataQueryTool(
    "../data_pack/raw/turbine_telemetry_14day_sample.csv",
    "../data_pack/raw/dam_price_14day_sample.csv"
)

In [7]:
result = tool.turbine_summary("T01")

print(result)

{'rows': 336, 'average_power_kw': np.float64(428.0836309523809), 'maximum_power_kw': np.float64(2000.0), 'minimum_power_kw': np.float64(0.0), 'average_wind_speed': np.float64(7.555327380952382), 'available_hours': np.int64(336)}

In [8]:
print(tool.dam_summary())

{'average_price': np.float64(5.1043988095238095), 'maximum_price': np.float64(9.635), 'minimum_price': np.float64(3.168)}

In [9]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [10]:
from part_a.tools.calculation_tools import CalculationTool

calculator = CalculationTool()

In [12]:
tool = DataQueryTool(
    "../data_pack/raw/turbine_telemetry_14day_sample.csv",
    "../data_pack/raw/dam_price_14day_sample.csv"
)

In [13]:
t01 = tool.turbine_summary("T01")

cf = calculator.capacity_factor(
    t01["average_power_kw"]
)

print("T01 capacity factor:", cf)

T01 capacity factor: 0.21404181547619044

In [18]:
from part_a.tools.rulebook_tool import RulebookTool

In [20]:
rulebook = RulebookTool(
    "../data_pack/compliance_rulebook.docx"
)

In [21]:
result = rulebook.lookup("temporal")

for line in result:
    print(line)

RFNBO Temporal Correlation — Compliance Rulebook
This is a simplified extract for the purposes of the assignment. It captures the structure of real RFNBO temporal correlation requirements without reproducing any specific regulation verbatim. Treat it as the source of truth for any question the agent needs to answer about compliance.
Electrolyzer electricity consumption in a given hour is considered temporally correlated with renewable generation if renewable output was greater than zero in that same clock hour, at the facility's home price/grid area.

In [22]:
result = rulebook.lookup("electrolyzer")

for line in result:
    print(line)

Electrolyzer electricity consumption in a given hour is considered temporally correlated with renewable generation if renewable output was greater than zero in that same clock hour, at the facility's home price/grid area.
Until the hourly-matching phase takes effect, correlation may be assessed on a monthly basis: total renewable generation for the calendar month must be greater than or equal to total electrolyzer consumption for that month, even if individual hours don't match.
Once hourly matching applies, correlation must be assessed per hour: for each hour of electrolyzer operation, renewable generation in that same hour must be greater than or equal to electrolyzer consumption in that hour. A month with 90% or more of its hours individually compliant is treated as compliant for that month; below 90%, the month fails regardless of the monthly total.
Any electrolyzer consumption sourced from grid purchases (as opposed to directly metered renewable output) does not count toward correlation, even if renewable generation was available at the same hour, unless a matching power purchase agreement with hourly attribution is in place.

In [23]:
result = rulebook.lookup("hourly")

for line in result:
    print(line)

Until the hourly-matching phase takes effect, correlation may be assessed on a monthly basis: total renewable generation for the calendar month must be greater than or equal to total electrolyzer consumption for that month, even if individual hours don't match.
Rule 3 — Hourly matching (future phase)
Once hourly matching applies, correlation must be assessed per hour: for each hour of electrolyzer operation, renewable generation in that same hour must be greater than or equal to electrolyzer consumption in that hour. A month with 90% or more of its hours individually compliant is treated as compliant for that month; below 90%, the month fails regardless of the monthly total.
Any electrolyzer consumption sourced from grid purchases (as opposed to directly metered renewable output) does not count toward correlation, even if renewable generation was available at the same hour, unless a matching power purchase agreement with hourly attribution is in place.
Compliance reporting must be produced at hourly granularity once Rule 3 applies, and at monthly granularity under Rule 2. Reports must state which rule (2 or 3) was applied and why.

In [24]:
result = rulebook.lookup("temporal")

print(result)

['RFNBO Temporal Correlation — Compliance Rulebook', 'This is a simplified extract for the purposes of the assignment. It captures the structure of real RFNBO temporal correlation requirements without reproducing any specific regulation verbatim. Treat it as the source of truth for any question the agent needs to answer about compliance.', "Electrolyzer electricity consumption in a given hour is considered temporally correlated with renewable generation if renewable output was greater than zero in that same clock hour, at the facility's home price/grid area."]

In [ ]:
result = rulebook.lookup("battery_storage")

print(result)

[]

:

In [2]:
import sqlite3
import pandas as pd
from pathlib import Path

# --------------------------------------------------
# Paths
# --------------------------------------------------

BASE_DIR = Path("..")

TURBINE_FILE = BASE_DIR / "data_pack" / "raw" / "turbine_telemetry_14day_sample.csv"
DAM_FILE = BASE_DIR / "data_pack" / "raw" / "dam_price_14day_sample.csv"

DB_FILE = BASE_DIR / "data_pack" / "greenko_part_a.db"


# --------------------------------------------------
# Load CSV files
# --------------------------------------------------

turbine_df = pd.read_csv(TURBINE_FILE)
dam_df = pd.read_csv(DAM_FILE)

print("Turbine data:")
display(turbine_df.head())

print("\nDAM data:")
display(dam_df.head())


# --------------------------------------------------
# Inspect columns
# --------------------------------------------------

print("Turbine columns:")
print(turbine_df.columns.tolist())

print("\nDAM columns:")
print(dam_df.columns.tolist())


# --------------------------------------------------
# Create SQLite database
# --------------------------------------------------

conn = sqlite3.connect(DB_FILE)


# --------------------------------------------------
# Write tables
# --------------------------------------------------

turbine_df.to_sql(
    "turbine_telemetry",
    conn,
    if_exists="replace",
    index=False
)

dam_df.to_sql(
    "dam_prices",
    conn,
    if_exists="replace",
    index=False
)


# --------------------------------------------------
# Verify tables
# --------------------------------------------------

print("\nTables created successfully.")

print(
    pd.read_sql(
        "SELECT name FROM sqlite_master WHERE type='table';",
        conn
    )
)


# --------------------------------------------------
# Test turbine table
# --------------------------------------------------

print("\nTurbine table:")
display(
    pd.read_sql(
        "SELECT * FROM turbine_telemetry LIMIT 5;",
        conn
    )
)


# --------------------------------------------------
# Test DAM table
# --------------------------------------------------

print("\nDAM table:")
display(
    pd.read_sql(
        "SELECT * FROM dam_prices LIMIT 5;",
        conn
    )
)


conn.close()

print(f"\nDatabase saved at: {DB_FILE}")

Turbine data:

             timestamp turbine_id  wind_speed  power_kw  availability
0  2026-03-01 00:00:00        T01        7.11     198.3           1.0
1  2026-03-01 00:00:00        T02        5.42      25.6           1.0
2  2026-03-01 00:00:00        T03        8.31     393.2           1.0
3  2026-03-01 00:00:00        T04        4.82      11.3           1.0
4  2026-03-01 00:00:00        T05        4.24      27.3           1.0

DAM data:

             timestamp  dam_price_inr_per_kwh
0  2026-03-01 00:00:00                  4.255
1  2026-03-01 01:00:00                  4.330
2  2026-03-01 02:00:00                  4.186
3  2026-03-01 03:00:00                  4.032
4  2026-03-01 04:00:00                  4.141

Turbine columns:
['timestamp', 'turbine_id', 'wind_speed', 'power_kw', 'availability']

DAM columns:
['timestamp', 'dam_price_inr_per_kwh']

Tables created successfully.
                name
0  turbine_telemetry
1         dam_prices

Turbine table:

             timestamp turbine_id  wind_speed  power_kw  availability
0  2026-03-01 00:00:00        T01        7.11     198.3           1.0
1  2026-03-01 00:00:00        T02        5.42      25.6           1.0
2  2026-03-01 00:00:00        T03        8.31     393.2           1.0
3  2026-03-01 00:00:00        T04        4.82      11.3           1.0
4  2026-03-01 00:00:00        T05        4.24      27.3           1.0

DAM table:

             timestamp  dam_price_inr_per_kwh
0  2026-03-01 00:00:00                  4.255
1  2026-03-01 01:00:00                  4.330
2  2026-03-01 02:00:00                  4.186
3  2026-03-01 03:00:00                  4.032
4  2026-03-01 04:00:00                  4.141

Database saved at: ..\data_pack\greenko_part_a.db